Default: &defaults
  database: lambdacat.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: lambdacat_test.sqlite3
  <<: *defaults

Staging:
  database: lambdacat_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: lambdacat_production.sqlite3
  poolsize: 100
  <<: *defaults
